config/routes.rb
NatesPhotos::Application.routes.draw do

  get "static_pages/index" => 'static_pages#index'
  get "static_pages/photography" => 'static_pages#photography', :path => '/photography', as: 'photography'
  get "static_pages/set-page" => 'static_pages#set_page', :path => 'photography/set-page', as: 'set_page'
  get "static_pages/cinematography" => 'static_pages#cinematography', :path => '/cinematography', as: 'cinematography'
  get "static_pages/video-page" => 'static_pages#video_page', :path => 'cinematogrpahy/video-page', as: 'video_page'
  root :to => "static_pages#index"

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def photography
  end

  def set_page
  end

  def cinematography
  end

  def video_page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def on_detail_page?
    (controller_name == "static_pages" and action_name == "set_page")
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.haml
!!!
%html#html-top
  %head
    %title NATHAN MCGARIGAL
    = stylesheet_link_tag    "application", media: "all"
    = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic", media: "all"

    = javascript_include_tag "application"
    = javascript_include_tag "http://a.vimeocdn.com/js/froogaloop2.min.js"
    = csrf_meta_tags
  %body{:class => "#{action_name}"}
    - if on_detail_page?
      #detail-page.clearfix
        = render "shared/detail_page_menu"
        = yield
    - else
      = render "shared/primary_menu"
      = yield
      = render "shared/footer"
      
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-53428196-1', 'auto');
      ga('send', 'pageview');

app/views/shared/_detail_page_menu.html.haml
#detail-page-menu
  %h2 
    =link_to 'NATHAN MCGARIGAL', root_path

  =link_to 'photography', photography_path, :class => 'detail-type'

  %h3.detail-title Gallery Name
  
  =link_to image_tag('close-button.png'), "#", :class => 'close-button', :id => 'close-gallery'
  

app/views/shared/_footer.html.haml
%footer#footer
  #footer-wrap
    %h2 
      =link_to 'NATHAN MCGARIGAL', '#html-top'
      =link_to image_tag('up-arrow.png'), '#html-top'
      =link_to 'top', '#html-top', :class => 'top-message'
    
    %ul.contact-links
      %li 
        =link_to 'photography', photography_path, :id => 'link-photo-page'
      %li 
        =link_to 'cinematography', cinematography_path, :id => 'link-video-page'
      %li
        %span phone:
        413-687-1445
      %li
        %span email:
        nathanmcgarigal@yahoo.com
      %li
        IATSE Local 600
    %ul.personal-links
      %li follow me on:
      %li 
        =link_to image_tag('icon-flickr.png'), 'https://www.flickr.com/photos/mcgarigal/', :target => '_blank'
      %li
        =link_to image_tag('icon-ig.png'), 'http://instagram.com/mcgarigal', :target => '_blank'
      %li
        =link_to image_tag('icon-fb.png'), 'https://www.facebook.com/mcgarigal', :target => '_blank'

app/views/shared/_primary_menu.html.haml
#primary-menu
  %h2 
    =link_to 'NATHAN MCGARIGAL', '#footer'
  %ul
    %li
      =link_to 'Photography', photography_path, :class => 'nav-link'
    %li
      =link_to 'Cinematography', cinematography_path, :class => 'nav-link'

app/views/static_pages/cinematography.html.haml
= javascript_include_tag "videos" 
- content_for :title, 'cinematography'
#video-page-preloader
#cinematography-page
  %ul.clearfix#thumbs 
    =image_tag('preloader-white.gif', :id => "preloader-video")
  
  #detail-page.video-page
    = render "shared/detail_page_menu"
    #video-slider.rsDefault
    

app/views/static_pages/photography.html.haml
= javascript_include_tag "photographs" 
- content_for :title, 'photographs'

=image_tag('preloader-white.gif', :id => "preloader-video")

%ul#photo-sets.clearfix


#detail-page.hidden
  = render "shared/detail_page_menu"
  .photo-slider.rsDefault

app/views/static_pages/set_page.html.haml
.photo-slider.rsDefault
  =image_tag('tmp-1.gif', :class => "rsImg", :data_rsTmb => "tmp-1.gif")
  =image_tag('tmp-2.gif', :class => "rsImg", :data_rsTmb => "tmp-2.gif")
  =image_tag('tmp-3.gif', :class => "rsImg", :data_rsTmb => "tmp-3.gif")
  =image_tag('tmp-4.gif', :class => "rsImg")
  =image_tag('tmp-5.gif', :class => "rsImg")
  =image_tag('tmp-6.gif', :class => "rsImg")
  =image_tag('tmp-7.gif', :class => "rsImg")
  =image_tag('tmp-8.gif', :class => "rsImg")
  =image_tag('tmp-9.gif', :class => "rsImg")

app/views/static_pages/video_page.html.haml
%h1 StaticPages#video-page
%p Find me in app/views/static_pages/video-page.html.haml